### ISSUE TITLE
Error loading libRSSupport library

### ISSUE THREAD

**Issue by IlyaMyasoedov** [Manabu-GT/EtsyBlur#12]
Hi...
When launch the demo app, i get the exception...
My devide - ZTE Geek v975, Android 4.2.2
The log is attached in txt
[log (2).txt](https://github.com/Manabu-GT/EtsyBlur/files/52134/log.2.txt)

**Comment by Manabu-GT** [comment]
It turns out renderscript is not supported on armabi architecture. It's only available for armeabi-v7a.
I will add a fallback method not to crash.
