### ISSUE TITLE
Library depends on you

### ISSUE THREAD

**Issue by egslava** [Manabu-GT/EtsyBlur#6]
Hi!
I need a library to implement blurred images in app (blurred user avatar as a profile background). So I just used your library (very thanks! :-), wrapped it to around ImageView and [share][1] throw bintray/github.

Is it legal?

[1]: https://github.com/egslava/BlurredImageView

**Comment by Manabu-GT** [comment]
Yes, it is legal as long as you include my license as well.
So, in your license file, just include "Copyright 2014 Manabu Shimobe" and you should be fine.
