### ISSUE TITLE
Screen Edge don't Blur

### ISSUE THREAD

**Issue by MohHeader** [Manabu-GT/EtsyBlur#7]
First, I would like to thank you for your effort,

I have some sort of issue where The Activity Screen is not Fully blurred,
as a slim part of it is not blurred, 

i.e. if the Drawer is from the left, ( The far edge on the right is not blurred )

Thanks,

**Comment by MohHeader** [comment]
I found the reason ( But not solved yet )

The Image that is taken for the activity is ( Transparent ) That's why some part's appear not blurred. ( Behind the transparent area )

**Comment by MohHeader** [comment]
Workaround : 

~~~~xml
android:background="?android:colorBackground"
~~~~

But still hope that there is a native solution

**Comment by Manabu-GT** [comment]
I don't know if you are still looking for a solution, but I added "overlayColor"(color used to overrlay the blurred image) option in v0.2.0 and you could probably use it instead of the above workaround.

Thanks.
