### ISSUE TITLE
Does this work pre API 17?

### ISSUE THREAD

**Issue by danieljonker** [Manabu-GT/EtsyBlur#8]
I noticed the min sdk is 8 but it uses ScriptIntrinsicBlur which was added in api 17.
http://developer.android.com/reference/android/renderscript/ScriptIntrinsicBlur.html

**Comment by Manabu-GT** [comment]
Yes, since it uses the renderscript api in the support library which requires api level 8 and higher.
http://developer.android.com/reference/android/support/v8/renderscript/package-summary.html
